services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PG_PASS}"
    ports:
      - "5432:5432"
    volumes:
      - pg-persist:/var/lib/postgresql/data

volumes:
  pg-persist:
